vich_uploader:
    db_driver: orm

    mappings:
      produit_image:
        uri_prefix: /images/produit
        upload_destination: '%kernel.project_dir%/public/images/produit'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
